### ISSUE TITLE
Catalina Compatibility Issue

### ISSUE THREAD

**Issue by AxelDeneu** [ajgagnon/projecthuddle-sketch-sync#2]
Hello !

At the time of writing I'm experiencing a bug with the plugin.

Sometimes, when I try to interact with it by just opening the plugin form it makes my Sketch crash.

Sometimes, the plugin opens but is completly blank, as follow :
<img width="420" alt="CleanShot 2019-10-24 at 13 42 40@2x" src="https://user-images.githubusercontent.com/22771331/67482537-2c2fbf80-f664-11e9-90b0-7bb254d4f873.png">

I can interact with the form input but when i try to, it crashes my Sketch with the following error in the console (I started the plugin via the console like mentionned in the development tutorial) :
`*** Terminating app due to uncaught exception 'NSInvalidReceivePortException', reason: 'connection went invalid while waiting for a reply because a mach port died'
***`

When I try the .sketchplugin version it does the same.

That bug wasn't happening when I was on High Sierra.

Is it a known issue on your side ?

**Comment by ajgagnon** [comment]
So sorry for the delay - I don't typically check the issues here. Can you reach out to support directly? 

Support@projecthuddle.io
